version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017

  conversations:
    build:
      context: .
      dockerfile: Dockerfile
    image: llm_interaction_api
    env_file: .env
    ports:
      - 3000:3000
